name: Deploy Frontend

on:
  push:
    branches: ["main"]

jobs:
  push-frontend:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout FRONTEND
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git config --global user.name ${{ secrets.PERSONAL_USERNAME }}
          git config --global user.email ${{ secrets.PERSONAL_EMAIL }}

      - name: Clone and copy FRONTEND
        run: |
          rm -rf .git || true
          git clone https://${{ secrets.PERSONAL_USERNAME }}:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ secrets.PERSONAL_USERNAME }}/${{ secrets.PERSONAL_FRONTEND_REPO }}.git
          cp -rT FRONTEND/ ${{ secrets.PERSONAL_FRONTEND_REPO }}/

      - name: Commit push FRONTEND
        working-directory: ${{ secrets.PERSONAL_FRONTEND_REPO }}
        run: |
          git branch -M main || true
          git checkout main || true
          git add --all
          git commit --allow-empty -m "CI/CD: Copied FRONTEND"

      - name: Push to remote repository
        working-directory: ${{ secrets.PERSONAL_FRONTEND_REPO }}
        run: |
          git remote add cheat-origin https://${{ secrets.PERSONAL_USERNAME }}:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ secrets.PERSONAL_USERNAME }}/${{ secrets.PERSONAL_FRONTEND_REPO }}.git
          git push -u cheat-origin main