name: Deploy Frontend

on:
  push:
    branches: ["main"]

jobs:
  push-frontend:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout FRONTEND
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git config --global user.name ${{ secrets.PERSONAL_USERNAME }}
          git config --global user.email ${{ secrets.PERSONAL_EMAIL }}

      - name: Clone and clean cheated repo
        run: |
          git clone https://${{ secrets.PERSONAL_USERNAME }}:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ secrets.PERSONAL_USERNAME }}/${{ secrets.PERSONAL_FRONTEND_REPO }}.git /tmp/${{ secrets.PERSONAL_FRONTEND_REPO }}
          cd /tmp/${{ secrets.PERSONAL_FRONTEND_REPO }}
          git rm -rf .
          git clean -fxd

      - name: Copy FRONTEND
        run: |
          rm -rf .git || true
          cp -a ./. /tmp/${{ secrets.PERSONAL_FRONTEND_REPO }}
          rm -f /tmp/${{ secrets.PERSONAL_FRONTEND_REPO }}/.github/workflows/frontend.yml

      - name: Commit push FRONTEND
        working-directory: /tmp/${{ secrets.PERSONAL_FRONTEND_REPO }}
        run: |
          git branch -M main || true
          git checkout main || true
          git add --all
          git commit --allow-empty -m "CI/CD: Copied frontend from ${{ github.sha }}"

      - name: Push to remote repository
        working-directory: /tmp/${{ secrets.PERSONAL_FRONTEND_REPO }}
        run: |
          git remote add cheat-origin https://${{ secrets.PERSONAL_USERNAME }}:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ secrets.PERSONAL_USERNAME }}/${{ secrets.PERSONAL_FRONTEND_REPO }}.git
          git push -u cheat-origin main
