name: Test
on: pull_request

jobs:
  build:
    name: CI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          install_before_time=$(date +%s.%N)
          yarn install --frozen-lockfile
          install_after_time=$(date +%s.%N)
          install_time=$(python -c "print($install_after_time - $install_before_time)")
          echo "installTime=$install_time" >> $GITHUB_ENV

      - name: Build Website
        run: |
          before_time=$(date +%s.%N)
          yarn build
          after_time=$(date +%s.%N)
          build_time=$(python -c "print($after_time - $before_time)")
          echo "buildTime=$build_time" >> $GITHUB_ENV

      - name: Verify Build Output
        run: |
          if [ -d ".next" ]; then
            echo "Build successful"
          else
            echo "Build failed"
            exit 1
          fi
